### ISSUE TITLE
test failures on ppc64/ppc64le and armv7

### ISSUE THREAD

**Issue by sharkcz** [TieDyedDevil/XS#10]
The current HEAD fails to pass the test suite on ppc64/ppc64le and armv7 architectures, same failures on all 3 arches.

[3/4] '/usr/bin/python3' '/usr/bin/meson' '--internal' 'commandrunner' '/builddir/build/BUILD/XS-fc45d1fa6995705c8ac6d78cf102a6aac682828f' '/builddir/build/BUILD/XS-fc45d1fa6995705c8ac6d78cf102a6aac682828f/build' '' '/usr/bin/mesonintrospect' 'sh' '-c' './tests/xs_tests.xs'
Python detected LC_CTYPE=C: LC_CTYPE & LANG coerced to C.UTF-8 (set another locale or PYTHONCOERCECLOCALE=0 to disable this locale coercion behavior).
/builddir/build/BUILD/XS-fc45d1fa6995705c8ac6d78cf102a6aac682828f/./tests
Passed:  Simple alias operates
Passed:  Self-referring alias does not recurse
Passed:  Temporary alias disappears
Passed:  Alias print
Passed:  Simple addition
Passed:  Simple multiplication
Passed:  Simple division
Passed:  Simple modulus
Passed:  Simple subtraction
Passed:  Order of operations
Passed:  Floating point operation
Passed:  Let without assign
Passed:  Character hex escapes
Passed:  Character octal escapes
Passed:  Character Unicode escapes
Passed:  Character invalid escapes
Passed:  Simple until test
Passed:  Escape escapes
Passed:  Escape val
Passed:  Throw from escape
Passed:  echo
Passed:  Eval echo
Passed:  map produces expected values
Passed:  omap produces expected list
Passed:  solitary * matches all non-. files
Passed:  * glob matches expected files
Passed:  ? glob matches expected files
Passed:  */* glob matches expected files
Passed:  Command args match
Passed:  Failure on empty command
Passed:  Long word
Passed:  Backslash-newline to space conversion
Passed:  Backslash after variable terminates name
Passed:  Backslash-newline after variable name space conversion
Passed:  Backslash in middle of word
Passed:  Free-standing backslash
Passed:  EOF in comment
Passed:  Colon handled properly
Passed:  Equals in middle of word is literal
Passed:  Equals at end of word is literal
Passed:  Equals at beginning of word is literal
Passed:  Free-standing equals incorectly placed fails
Passed:  For across infix list
Passed:  printf %s
Passed:  printf %s w/ width
Passed:  printf %s w/ left
Passed:  printf %s w/ precision
Passed:  printf %c
Passed:  printf %c w/ non-char arg
Passed:  printf %d
Passed:  printf %d w/ non-integral numeric arg
Passed:  printf %d w/ non-numeric arg
Passed:  printf %i
Passed:  printf %i w/ non-integral numeric arg
Passed:  printf %i w/ non-numeric arg
Passed:  printf %o
Passed:  printf %o w/ non-integral numeric arg
Passed:  printf %o w/ non-numeric arg
Passed:  printf %u
Passed:  printf %u w/ non-integral numeric arg
Passed:  printf %u w/ non-numeric arg
Passed:  printf %x
Passed:  printf %x w/ non-integral numeric arg
Passed:  printf %x w/ non-numeric arg
Passed:  printf %X
Passed:  printf %X w/ non-integral numeric arg
Passed:  printf %X w/ non-numeric arg
{match 3.140000 -2.718000} failed
Failed:  printf %f
{match 73.000000 -32.000000} failed
Failed:  printf %f w/ integral numeric arg
Passed:  printf %f w/ non-numeric arg
{match 3.140000e+00 -2.718000e+00} failed
Failed:  printf %e
{match 7.300000e+01 -3.200000e+01} failed
Failed:  printf %e w/ integral numeric arg
Passed:  printf %e w/ non-numeric arg
{match 3.140000E+00 -2.718000E+00} failed
Failed:  printf %E
{match 7.300000E+01 -3.200000E+01} failed
Failed:  printf %E w/ integral numeric arg
Passed:  printf %E w/ non-numeric arg
{match 3.14 -2.718 0.0001 1e-05} failed
Failed:  printf %g
{match 73 -32 100000 1e+06} failed
Failed:  printf %g w/ integral numeric arg
Passed:  printf %g w/ non-numeric arg
{match 3.14 -2.718 0.0001 1E-05} failed
Failed:  printf %G
{match 73 -32 100000 1E+06} failed
Failed:  printf %G w/ integral numeric arg
Passed:  printf %g w/ non-numeric arg
Passed:  printf %a w/ non-numeric arg
Passed:  printf %a w/ non-numeric arg
Passed:  Pushd absolute
Passed:  Pushd relative
Passed:  Pushd (no args)
Passed:  Bad command output redirection
Passed:  Bad command input redirection
Passed:  Integer :lt comparison
Passed:  Integer :le comparison
Passed:  Integer :gt comparison
Passed:  Integer :ge comparison
Passed:  Integer :eq comparison
Passed:  Integer :ne comparison
Passed:  Float :lt comparison
Passed:  Float :le comparison
Passed:  Float :gt comparison
Passed:  Float :ge comparison
Passed:  Float :eq comparison
Passed:  Float :ne comparison
Passed:  Float :lt comparison
Passed:  Integer/Float :le comparison
Passed:  Integer/Float :gt comparison
Passed:  Integer/Float :ge comparison
Passed:  Integer/Float :eq comparison
Passed:  Integer/Float :ne comparison
Passed:  Float/Integer :lt comparison
Passed:  Float/Integer :le comparison
Passed:  Float/Integer :gt comparison
Passed:  Float/Integer :ge comparison
Passed:  Float/Integer :eq comparison
Passed:  Float/Integer :ne comparison
Passed:  String :lt comparison
Passed:  String :le comparison
Passed:  String :gt comparison
Passed:  String :ge comparison
Passed:  String :eq comparison
Passed:  String :ne comparison
Passed:  fsplit
Passed:  split
Passed:  Subscript one valid index
Passed:  Subscript one zero index
Passed:  Subscript one negative index
Passed:  Subscript index past end
Passed:  Subscript one definite range
Passed:  Subscript one open beginning range
Passed:  Subscript one open ending range
Passed:  Subscript one reversed definite range
Passed:  Subscript mixed
Passed:  Subscript one range bad start
Passed:  Subscript one range bad end
Passed:  Subscript missing index
Passed:  switch_normal
Passed:  switch_default
Passed:  XS let precise error
Passed:  Syntax error on bad let
-------  No ppc64le platform tests
Expected passes:      127
Unexpected failures:  10
FAILED: check 

For full details please build.log files at https://koji.fedoraproject.org/koji/taskinfo?taskID=19712683

**Comment by sharkcz** [comment]
xs_tests.log as txt file
[xs_tests.log.txt](https://github.com/TieDyedDevil/XS/files/1028845/xs_tests.log.txt)

**Comment by TieDyedDevil** [comment]
Thank you for the log.

Please try 22afec1 or later.

I was using libffi to call a variadic print function with the wrong (non-variadic) FFI description.

My guess, not having done a deep dive into arm7 and ppc64 calling conventions, is that they pass float args differently from integral args.

**Comment by sharkcz** [comment]
thanks, all is green now - https://koji.fedoraproject.org/koji/taskinfo?taskID=19727773

**Comment by TieDyedDevil** [comment]
Great! Thank you.
