### ISSUE TITLE
auto completion does not handle filenames with spaces, ', and ~ in it well

### ISSUE THREAD

**Issue by L-as** [TieDyedDevil/XS#15]
I tried deleting a file named `Simple mixer control 'FRDDR_A SINK 1 SEL',0`, and entered `rm Sim<tab><return>` to do it, but it autocompleted into `'Simple mixer control 'FRDDR_A SINK 1 SEL',0'` instead deleted `Simple mixer control FDDR_A`, `SINK`, `1`, `SEL,0`, which was obviously not intended. I assume this is a bug in XS?

**Comment by TieDyedDevil** [comment]
Thanks. That is a known issue (see doc/NOTES).

I work around this issue by typing a ' at the start of a filename which contains whitespace or '; after completion, the internal 's must be manually doubled.

If this ever gets to the point where I'm annoyed enough to wrestle again with GNU readline, I'll take a shot at making completion work as expected.

**Comment by L-as** [comment]
I found another issue: Filenames with a `~` in them. E.g. inside a directory with only one file named `a ~b` in it, pressing tab once gives `/home/myusernameb`

**Comment by TieDyedDevil** [comment]
Resolved by https://github.com/TieDyedDevil/XS/commit/d65d35eb054e9d68693f985b12c38aa42c9549d9
