### ISSUE TITLE
signal.cxx:289: bad loop 

### ISSUE THREAD

**Issue by dcb314** [TieDyedDevil/XS#3]
signal.cxx:289:3: warning: loop exit may only be reached after undefined behavior [-Waggressive-loop-optimizations]

```
for (sig = 0;; sig++) {
    if (caught[sig] != 0) {
        --sigcount;
        caught[sig] = 0;
        break;
    }
    if (sig >= NSIG) {
        sigcount = 0;
        return;
    }
}
```

Suggest check sig < nSIG _before_ indexing into array.

**Comment by TieDyedDevil** [comment]
Closed via ebd5155.
