### ISSUE TITLE
Building XS

### ISSUE THREAD

**Issue by ghost** [TieDyedDevil/XS#4]
I'm interested in XS. I read the INSTALL file, which states that I simply need to run:

```
./configure
make
```

But that's not the case. A configure file has not been generated in the current tree, so the initial ./configure does not work. I applied what I know of autotools to try and build it anyway, but I'm too retarded to get it to work. I got to a point where the Makefile was generated, but make required a ‘parse.h’, which is not present. There's parse.yxx, though. There's another issue here (https://github.com/frytvm/XS/issues/2) in which it was suggested to run bison on parse.yxx. I am not at all familiar with bison and I believe I am doing something incorrectly, as `bison parse.yxx` generates a parse.tab.cxx file instead of the parse.hxx as stated in the other issue. I'm kind of lost here.

**Comment by frkoehle** [comment]
Hi,

I pushed a new revision that should fix the issues, please try it. Thanks
for your interest!

**Comment by ghost** [comment]
That works! Thank you sir!

But there's still a couple small problems. Firstly, the `compile` and `missing` files are now symlinks to their respective locations in automake-1.14. I'm on Gentoo and the latest release of automake (without explicitly enabling keywords) as far as I can tell is 1.13, so the symlink was pointing to a nonexistent directory. I fixed that locally, though, I just thought you should be aware of this. The INSTALL file still says to do `./configure` and `make`, but one first needs to run `autoreconf` before running those other commands as `configure` is not present.

I might seek to contribute to XS sometime within the coming months. It's a cool project and I've been wanting RC or something similar to be revived on *nix.

**Comment by ormaaj** [comment]
Build works here (gentoo amd64). This is indeed an interesting project.

**Comment by frkoehle** [comment]
Okay, I tried to fix the INSTALL file instructions and the repo to not have
symlinks, hopefully things are good now.

**Comment by ghost** [comment]
All seems to be in order. Thankya :)
![screenie](https://cloud.githubusercontent.com/assets/3895638/5694851/82973a10-993a-11e4-8e27-c5dccbd205fb.png)

**Comment by ghost** [comment]
I am wondering, though, how to use a command as a prompt or to get similar functionality to what `\$` would provide in bash.

I am also wondering how XS is configured. What is the XS equivalent of bourne-alikes' /etc/profile , .bashrc , .zshrc, etc.?

I'm sorry for asking these questions here. Ideally, I would ask them in IRC or something, but I haven't seen a better medium for these questions in the context of XS.

**Comment by frkoehle** [comment]
Maybe this is too late, but for future reference
the startup file is ~/.xsrc
to get a dynamic prompt, you can can combine the variable $prompt and function %prompt:
fn %prompt { $prompt = `pwd^\$\  }
[to see these sorts of things, look at initial.xs]
these things should be documented in the manfile better
but i am quite busy so it will be a while before i do so myself

**Comment by TieDyedDevil** [comment]
No longer built with autotools. Now using Meson/Ninja.

The new `samples` directory contains extended examples of prompt manipulation.
