### ISSUE TITLE
Request: Vi Keybindings

### ISSUE THREAD

**Issue by ghost** [TieDyedDevil/XS#8]
Hell, I might do this myself come summer break. I'm used to vi keybindings, so a vi mode would be great.

**Comment by wryun** [comment]
If you're using readline, it's already there:

http://cnswww.cns.cwru.edu/php/chet/readline/readline.html#SEC22

**Comment by TieDyedDevil** [comment]
Edit your `~/.inputrc` file to include a `set editing-mode vi` line. I also find `set show-mode-in-prompt on` to be useful.

Consult `info readline` for other settings.
